version: '3'
services:
  unique-service:
    stdin_open: true
    tty: true
    command: ['nodemon']
    volumes:
      - ./src/controllers:/src/controllers
      - ./src/integration-test:/src/integration-test
      - ./src/lib:/src/lib
      - ./src/middleware:/src/middleware
      - ./src/migrations:/src/migrations
      - ./src/models:/src/models
      - ./src/routes:/src/routes
      - ./src/scripts:/src/scripts
      - ./src/validators:/src/validators
      # Don't mount the local copy of node_modules, for compatibility reasons
      - /src/node_modules
    ports:
      - '4000:4000'
      - '9229:9229'
