version: '3'
services:
  unique-service:
    stdin_open: true
    tty: true
    command: ['npm', 'run', 'test-interactive']
    volumes:
      - ./coverage:/src/coverage
      - ./src:/src
      # Don't mount the local copy of node_modules, for compatibility reasons
      - /node_modules
